--INSERT INTO USUARIO (ID, PASSWORD, USERNAME) VALUES (1,'HA','HA');
--INSERT INTO USUARIO (ID, PASSWORD, USERNAME) VALUES (2,'CDIGITAIS','CDIGITAIS');
--INSERT INTO USUARIO (ID, PASSWORD, USERNAME) VALUES (3,'ECM','ECM');
--INSERT INTO USUARIO (ID, PASSWORD, USERNAME) VALUES (4,'PORTAL','PORTAL');
--INSERT INTO USUARIO (ID, PASSWORD, USERNAME) VALUES (5,'PEGA','PEGA');

--INSERT INTO ROLE (ID, NAME) VALUES (1,'HA');
--INSERT INTO ROLE (ID, NAME) VALUES (2,'CDIGITAIS');
--INSERT INTO ROLE (ID, NAME) VALUES (3,'ECM');
--INSERT INTO ROLE (ID, NAME) VALUES (4,'PORTAL');
--INSERT INTO ROLE (ID, NAME) VALUES (5,'PEGA');

--INSERT INTO USUARIO_ROLE (USUARIO_ID, ROLES_ID) VALUES (1,1);
--INSERT INTO USUARIO_ROLE (USUARIO_ID, ROLES_ID) VALUES (2,2);
--INSERT INTO USUARIO_ROLE (USUARIO_ID, ROLES_ID) VALUES (3,3);
--INSERT INTO USUARIO_ROLE (USUARIO_ID, ROLES_ID) VALUES (4,4);
--INSERT INTO USUARIO_ROLE (USUARIO_ID, ROLES_ID) VALUES (5,5);
